#!/bin/bash

# create the status of a file and write it into another file. the status
# contains a filename without, whitespace, permissions, owner, group, size and
# a sha1 checksum
# $1 file to inspect
# $2 file to write the status into
function createStatusAndAppendToFile {
        # $1 is the file to inspect
        fileToInspect=$1
        # $2 is the file in which the status gets written
        fileToWriteTo=$2
        fileStatus=`ls -l "$fileToInspect"`
        set -- junk $fileStatus
        shift
        permissions=$1
        owner=$3
        group=$4
        size=$5
        checkSum=`sha1sum "$fileToInspect" | cut --characters=1-40`
        fileToInspect=`echo "$fileToInspect" | sed 's/ /\\\n/g'`
        echo $fileToInspect $permissions $owner $group $size $checkSum >> $fileToWriteTo
}

# create a status file of the given directory in $1 and save it to $2
# get all files of the given directory $ $1 and create its status
find "$1" -type f -print0 2>/dev/null | while IFS= read -r -d '' filename; do
        createStatusAndAppendToFile "$filename" $2~
done

# sort the file
sort $2~ > $2
rm $2~

exit 0
